version: '3'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - '9187:9187'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - '9187:9187'
    environment:
      DATA_SOURCE_NAME: postgresql://postgres_exporter:odoo@192.168.56.10:5432/postgres?sslmode=disable
    tty: true
    restart: always
volumes:
  grafana_storage: {}